spring.application.name=ApiInventario

# ===============================
# \ud83d\udd10 JWT CONFIG
# ===============================
jwt.secret=8fK29sLxPqZ93mVtY7dR2nXcW6bAqH1kLmN0oPzQxYtVuEw
jwt.expiration=3600000


# ===============================
# \ud83d\uddc4\ufe0f DATABASE (POSTGRESQL)
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/inventarionuevo
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.datasource.driver-class-name=org.postgresql.Driver


# ===============================
# \ud83e\udde0 JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


# ===============================
# \ud83c\udf10 SERVER
# ===============================
server.port=8080


# ===============================
# \ud83e\uddfe LOGS (opcional)
# ===============================
logging.level.org.springframework.security=DEBUG


springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.defaultModelsExpandDepth=0